### PR TITLE
Fix the website width being slightly bigger than the screen width

### PR DESCRIPTION
**Pull request by tillson**
On the live website, the website seems to be unnecessarily wider than the browser screen, no matter what the size is.  This fixes it.

### CODE REVIEW

**Comment by tillson** [comment]
Apparently it also removes some unneeded whitespace (thanks Atom).

**Comment by kunalkundaje** [comment]
Hi @tillson. I was just made aware of this PR; thanks for submitting it!

Adding the `width: 100%;` property to the `.callout` class does fix the horizontal scroll issue, but also introduces a `-15px` margin on the right side due to the presence of the `row` class (see the screenshot below).

A better fix might be to simply remove the `row` class from this element on https://github.com/Netflix/netflix.github.com/blob/master/index.html#L134

If you update the PR with this fix, I'd be happy to go ahead and merge it for you.

pr-91

**Comment by tillson** [comment]
Done

**Comment by kunalkundaje** [comment]
Looks good. :+1: 

Merged via CLI.

**Pull request closed without merging**
